from enum import Enum 

class ErrorCode(Enum):
    COLUMN_NOT_FOUND = "COLUMN_NOT_FOUND"
    NON_NUMERIC_SUM_COLUMN = "NON_NUMERIC_SUM_COLUMN"
    MAX_SEARCH_CALLS_EXCEEDED = "MAX_SEARCH_CALLS_EXCEEDED"
    TOOL_EXECUTION_ERROR = "TOOL_EXECUTION_ERROR"
    READ_FAILURE = "READ_FAILURE"