name: Trigger auto deployment for cityagentbackend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ 148-backend-cicd ]
    paths:
    - '**'
    - '.github/workflows/cityagentbackend-AutoDeployTrigger-41f37a9a-d71d-4e2e-b4d1-2f864e352f11.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CITYAGENTBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CITYAGENTBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CITYAGENTBACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/backend
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: cityagentregistry.azurecr.io
          registryUsername: ${{ secrets.CITYAGENTBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CITYAGENTBACKEND_REGISTRY_PASSWORD }}
          containerAppName: cityagentbackend
          resourceGroup: CityAgentResourceGroup
          imageToBuild: cityagentregistry.azurecr.io/cityagentbackend:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


